### ISSUE TITLE
Picture frontpage

### ISSUE THREAD

**Issue by fjasteen** [inbo/craywatch#107]
@margotvermeylen & @biekemaex 
Like your channel pic, but, I would for sure take a picture of crayfish on the home page. From start on it makes it clear the project is about crayfish...

**Comment by margotvermeylen** [comment]
What do you think of the picture now?

**Comment by fjasteen** [comment]
And the marmerkreeft_invasief.jpg picture? We don't want them to seem to cute on our website...

**Comment by margotvermeylen** [comment]
I'll put it up to see how it looks. I don't think a lot of people will find them particularly cute though :)

**Comment by margotvermeylen** [comment]
Not sure I'm a fan of how this picture turned out in the banner...

**Comment by fjasteen** [comment]
@biekemaex I think this is a general problem. None of the chosen pictures on the banner has good resolution...

**Comment by peterdesmet** [comment]
Here's are a couple of front page banner suggestions. I suggest we vote on which we like best (compositionally, message). We can then brighten the image to offset the banner.

## Option 1 (current)

![Craywatch (6)](https://github.com/inbo/craywatch/assets/600993/152214b3-26cc-4a78-9b78-a36b79d42bf0)

## Option 2

![Craywatch (5)](https://github.com/inbo/craywatch/assets/600993/a429c944-b609-44f8-a68c-c101800670f8)

## Option 3

![Craywatch](https://github.com/inbo/craywatch/assets/600993/b349dde4-d4e1-423e-a119-734ccc53d26f)

## Option 4

![Craywatch (1)](https://github.com/inbo/craywatch/assets/600993/90946e14-5717-4f7e-9b3b-447802e1a269)

## Option 5

![Craywatch (4)](https://github.com/inbo/craywatch/assets/600993/fe820108-f85e-420d-8748-9ae198ca39cc)

## Option 6

![Craywatch (3)](https://github.com/inbo/craywatch/assets/600993/c41e347a-7300-43ce-a7ec-db5db3f11545)

**Comment by margotvermeylen** [comment]
I think I like 6 the best, but 2 and 4 also look good.

**Comment by peterdesmet** [comment]
Here's an adapted version of 6, that aligns better with the green banners used elsewhere:

![Craywatch](https://github.com/inbo/craywatch/assets/600993/6182a1ad-3d07-479f-ad19-3bd4206d118b)

**Comment by biekemaex** [comment]
Looks much better than the greyish image it was before!

**Comment by peterdesmet** [comment]
Updated, see https://craywatch.inbo.be/
