### ISSUE TITLE
Possible to add link to pdf?

### ISSUE THREAD

**Issue by biekemaex** [inbo/craywatch#112]
On the page https://craywatch.inbo.be/soorten/procambarus-acutus/  I would like to link to the signalementskaart from the Riparias website https://www.riparias.be/nl/355 

When you open this link on the riparias website, it automatically downloads a pdf - how can I link to this particular page?

**Comment by biekemaex** [comment]
Sorry, wrong link, we want to link to the links from this page https://www.iasregulation.be/350/

Will this link work in our website or does the "download" in the name make this something we can't just link to? https://www.iasregulation.be/770/download

**Comment by peterdesmet** [comment]
The RIPARIAS ones are annoying (can only download), but the IAS regulation ones can be linked to. Depending on your browser, it will display or download.

I have implemented this at https://craywatch.inbo.be/soorten/faxonius-limosus/ ([this commit](https://github.com/inbo/craywatch/commit/aaa480387f3688a00bf2240464335561e51f868b))

**Comment by biekemaex** [comment]
Perfect, I will do the same for the other species, thanks so much!
