### ISSUE TITLE
Gradient in banner photos?

### ISSUE THREAD

**Issue by biekemaex** [inbo/craywatch#114]
We noticed that all the photos we put in the banners have a gradient (become increasingly darker lower in the photo). This really affects the clarity of our photos. Can this effect be removed?

**Comment by peterdesmet** [comment]
This is by design, I would repeat the photo below. I'll create an example.

**Comment by peterdesmet** [comment]
See https://craywatch.inbo.be/soorten/faxonius-limosus/

To see the necessary changes, see https://github.com/inbo/craywatch/commit/b7420222368f75313a434e3c414e62f7bbb3b4e1
