### ISSUE TITLE
Species pictures

### ISSUE THREAD

**Issue by margotvermeylen** [inbo/craywatch#118]
I was adding pictures to the different species in the tiles on the 'soorten' page, and I noticed that that same picture is in the banner of that particular species page then too. To have it appear nice in the tiles, the picture is cropped in a way that it does not appear well in the banner. Is there a way to have the picture in the tile and in the banner of that species as different pictures? Thanks!

**Comment by peterdesmet** [comment]
No, it is the same picture in the banner as in the tile. The banner is more of a background image, so if you want a good picture on the species page itself, I would add it as a separate picture. I can add styling so that it doesn't take up the full page.
