### ISSUE TITLE
Update dropdown menu, add .md to pages/species/

### ISSUE THREAD

**Issue by fjasteen** [inbo/craywatch#15]
Add 'species'.md in  .pages/species/ to link from dropdown

**Comment by fjasteen** [comment]
The dropdown links have nowhere to link to in the pages as you added in the code. Can you make a seperate page for the other species?

**Comment by peterdesmet** [comment]
@fjasteen this commit https://github.com/inbo/craywatch/commit/1f1da4cd52871520c6f90571e50a557c9f419b28 introduces errors in the dropdown (e.g. the pages should have `-`, not `_` + there is no `species_index` page anymore). What do you want to achieve?

1. Hide links to pages that currently don't have content?
2. Link to a species overview page at https://craywatch.inbo.be/species/ (in addition to individual pages)?

**Comment by fjasteen** [comment]
Yes, you are correct.
I think Margots intention was to 
1. add additional species to the dropdown menu
2. therefore also new pages should be added in /pages/species/
@margotvermeylen can you have a look at it. I was to fast merging :-/

**Comment by margotvermeylen** [comment]
Yes I'm looking into it now!

**Comment by peterdesmet** [comment]
@margotvermeylen please link to the pages using `/species/pacifastacus-leniusculus/` (with `-`, not `_`). Also, if you want to link to the species index page, use `/species/` and add it as an extra element in the dropdown (you can't have `text` act as a dropdown menu _and_ link. You can assign me as reviewer for the PR.
