### ISSUE TITLE
Nederlands of Engels

### ISSUE THREAD

**Issue by peterdesmet** [inbo/craywatch#17]
@fjasteen @margotvermeylen Zal de website Nederlandstalig of Engelstalig zijn? Indien Nederlands, dan zou ik de pagina's (en hun URLs) ook naar het Nederlands wijzigen (dus `/soorten/`, `/locaties/`).

**Comment by margotvermeylen** [comment]
Gaat inderdaad in het Nederlands zijn, dus ik zal de namen van de pagina's wijzigen.

**Comment by peterdesmet** [comment]
Ok, je kan me opnieuw als reviewer aanduiden voor de PR.

**Comment by peterdesmet** [comment]
Fixed with #18
