### ISSUE TITLE
Add links from each species to each natuurpunt page

### ISSUE THREAD

**Issue by biekemaex** [inbo/craywatch#179]
Wij zouden graag op de pagina https://craywatch.inbo.be/waarnemingen/ nog eens elke rivierkreeft tonen (zoals op de soortenpagina) en dat elke kreeft linkt naar telkens de juiste pagina op waarnemingen.be (zoals op de pagina van flatwormwatch https://www.iasregulation.be/nl/flatwormwatch). De links naar waarnemingen.be kunnen we nog niet toevoegen, omdat ze nog niet bestaan, maar we kunnen de structuur wel al maken. 

Naast de 8 soorten kreeften moet er ook 1 knop zijn voor "ik heb geen kreeften gevangen - ik weet niet welke soort ik gevangen heb"

Op deze pagina zullen we ook een uitleg toevoegen over hoe mensen precies op die pagina's hun waarnemingen moeten ingeven.

**Comment by peterdesmet** [comment]
> juiste pagina op waarnemingen.be

Is het daar dat mensen zullen moeten rapporteren?

Zo'n pagina is te maken, maar als die zo goed zal lijken op https://craywatch.inbo.be/soorten/, vraag ik me af of we het dan niet beter combineren in 1 pagina, waarbij je op een soort klinkt, naar de soortpagina gaat en bovenaan een knop hebt om te rapporteren.

![Gevlekte-Amerikaanse-rivierkreeft-Craywatch](https://github.com/inbo/craywatch/assets/600993/f8830b08-eb30-427c-95ec-ead0d57b4678)

**Comment by biekemaex** [comment]
We zijn een beetje bang dat mensen die knop niet gaan zien op de soortenpagina of mensen die gewoon googlen over soorten kreeften gaan klikken zonder dat ze deel uitmaken van ons netwerk burgerwetenschappers.

Kunnen we er een soort beslissingsboom van maken?
1. Er zat vandaag minstens één kreeft in mijn vallen. ja/nee (nee linkt naar onbekend voor nulwaarnemingen (op waarnemingen.be)
ja: 2. Ik heb kunnen determineren om welke soort het gaat. ja/nee (nee linkt naar onbekend voor nulwaarnemingen)
ja 3. Dropdown (of andere handige weergave) waarbij ze op de juiste soort kunnen klikken en dan doorgestuurd worden naar de juiste soortenpagina op waarnemingen

**Comment by peterdesmet** [comment]
Er is misschien wel iets eenvoudig te maken (cf. uitklapsecties in https://craywatch.inbo.be/faq/), maar zou er dan niet uitzien als https://craywatch.inbo.be/soorten/ eerder als knoppen met namen van kreeften.

**Comment by biekemaex** [comment]
klinkt goed!

**Comment by biekemaex** [comment]
De links van natuurpunt zouden blijkbaar al vandaag online komen, dus eens die actief zijn kan ik ze toevoegen aan de beslissingsboom.

**Comment by fjasteen** [comment]
@biekemaex Dit zijn de links, je kunt ze toevoegen (ongeacht ze functioneel zijn)
https://waarnemingen.be/events/craywatch-procambarus-clarkii/
https://waarnemingen.be/events/craywatch-procambarus-acutus/
https://waarnemingen.be/events/craywatch-procambarus-virginalis/
https://waarnemingen.be/events/craywatch-faxonius-virilis/
https://waarnemingen.be/events/craywatch-faxonius-limosus/
https://waarnemingen.be/events/craywatch-pacifastacus-leniusculus/
https://waarnemingen.be/events/craywatch-pontastacus-leptodactylus/
https://waarnemingen.be/events/craywatch-astacus-astacus/
https://waarnemingen.be/events/craywatch-crayfish-indet/

**Comment by peterdesmet** [comment]
Ok, ik doe een poging

**Comment by biekemaex** [comment]
Ik kan zeker de links doen eens de structuur bestaat, Peter!

**Comment by peterdesmet** [comment]
Hebben we ook een link voor "linkt naar onbekend voor nulwaarnemingen"?

**Comment by biekemaex** [comment]
https://waarnemingen.be/events/craywatch-crayfish-indet/?

**Comment by peterdesmet** [comment]
Zie https://craywatch.inbo.be/waarnemingen/

**Comment by biekemaex** [comment]
yes, fantastisch!
