### ISSUE TITLE
Add link to full size pictures for better identification

### ISSUE THREAD

**Issue by damianooldoni** [inbo/craywatch#189]
I like that you added an image of the species in the species identification page. See https://craywatch.inbo.be/soorten/faxonius-limosus/#herkenning as example. In this way we have both: 
- a nice stylish banner (with gradient)
- a nice picture for identification

I was wondering, maybe it's better to add a link to this smaller images to open them full size? It's just an idea. Feel free to say no 😄

**Comment by biekemaex** [comment]
We still need to change all the images to clearer detailed photos, as we have already done for this one: https://craywatch.inbo.be/soorten/procambarus-acutus/ We haven't fully decided whether we still want to add more detailed photos as well, so we'll keep this issue open to make a final decision in the next few days :)

**Comment by margotvermeylen** [comment]
It might be nice indeed to be able to click on te image and have it enlarged. Is this hard to do @damianooldoni?
