### ISSUE TITLE
Can't use ND images

### ISSUE THREAD

**Issue by peterdesmet** [inbo/craywatch#19]
The [about](https://craywatch.inbo.be/info/) page has a background image with a CC-BY NC-ND license.

1. We cannot use such images on the website, since ND = Non Derivative and we are cropping the image.
2. In addition, the image links to https://bit.ly/3UwkD8u which is a generic search on waarnemingen.be

@fjasteen @margotvermeylen is there another image we can use?

**Comment by margotvermeylen** [comment]
Yes we definitely have pictures we can use for this. We'll look for some good ones!

**Comment by peterdesmet** [comment]
I notice the photo was used in 2 places:

- On the home page (a downloaded file). This has now been corrected in #24
- On the info page (a referenced file). It should be changed to another photo there too. It is also fine to use no photo. @biekemaex
