### ISSUE TITLE
Generate a csv with all locations

### ISSUE THREAD

**Issue by damianooldoni** [inbo/craywatch#205]
Specs:
- name: `locaties.gpkg` 
- format: GeoPackage
- storage: on GDrive folder SWO Rivierkreeften -> Data
- availability: open to everyone with the link
- it will contain at least the following fields: `locatieID`, `gemeente`, `provincie`, `postcode`, `x`, `y`

This file can be edited and updated during the project, e.g. by adding new locations.

@fjasteen will create this file and maintain it as far as I understood.
She will do some GIS operations (intersections,  ...) to get the needed information as defined in specs above.

**Comment by fjasteen** [comment]
@damianooldoni 

Done, 
- headers as asked, coordinates (x, y) but 'isGereserveerd' is 'isGereserv' due to limitation on number of characters in GIS
- saved as Localiteiten.csv in shared Data-folder
