### ISSUE TITLE
Naam op homepage veranderen naar Craywatch?

### ISSUE THREAD

**Issue by margotvermeylen** [inbo/craywatch#21]
Er staat nu nog 'De Kreeftenwacht' op de homepage, het project is nu officieel Craywatch denk ik.

**Comment by peterdesmet** [comment]
Hier aan te passen:

https://github.com/inbo/craywatch/blob/b5bf8b34a0d8b90b10ee2c6634c80657f98a71cc/pages/home.md?plain=1#L3
