### ISSUE TITLE
Show reserved locations on the map

### ISSUE THREAD

**Issue by damianooldoni** [inbo/craywatch#210]
Reserved locations are locations in `locaties.csv` where `isReserved` = `TRUE`.

These locations are **points** and will have to be shown as leaflet markers. By clicking on it a pop up should appear containing: `locatieID`, `gemeente`.

This layer must be shown by default.

**Comment by damianooldoni** [comment]
@fjasteen: the leaflet with the default layer is online. As written in the Pull Request #236, this is a dummy. But it is exactly the same as the file `locaties.csv` I will generate and maintain based on the geopackage you will provide. 
I will leave this issue open until the real map is shown. Feedback is also welcome!

**Comment by damianooldoni** [comment]
Some tasks still tackle:

- [ ] fetch the csv from GDrive. Notice that it's a csv, not a tabular gsheet published online and so directly downloadable. Still, this seems quite easy as the csv is publicly available.
- [ ] parse the csv correctly: it uses `;` as delimiter and `,` as decimal delimiter
- [ ] convert x-y coordinates from lambert to WGS84 (epsg code: 4326), supported by leaflet and the same coordinate system as the data of other layers

**Comment by damianooldoni** [comment]
PR #255 solved second and third step. Still to do:
[ ] Use real csv file with locations
[ ] Implement fetching data from GDrive

**Comment by damianooldoni** [comment]
I think that fetching data from GDrive is not optimal. By maintaining the csv file in this repo will allow us to trace changes so that if something gets wrong. You know, git can save us a lot of work.

To be discussed in a few hours with @fjasteen, @margotvermeylen and @biekemaex

**Comment by fjasteen** [comment]
Few changes to the localities.csv

- [ ] isGereserv column has become isReserved and has one of 3 values FALSE - TRUE - ONHOLD (when suggested)  @damianooldoni I think since you filter only TRUE-values, this might not be of importance for you. The suppresion of another isSuggested column and addition of a third category aids for a better visualization in GoogleMaps (point marker categorization)

- [ ] Transformation will be performed within Arcmap and latitude, longitude will be added to csv in respective columns for your convenience

- [ ] csv is now ',' delimited and decimals are represented by '.'

- [ ] save to github /assets/

**Comment by biekemaex** [comment]
Suggestion for a colour palette with 8 distinct colours: https://coolors.co/264653-287271-2a9d8f-8ab17d-e9c46a-f4a261-e76f51-eb886f

We think the Dark Matter and Grey Canvas maps are probably not necessary, the rest can stay!

**Comment by damianooldoni** [comment]
@fjasteen and I agreed on Thursday afternoon to maintain the locations as csv in this repo in folder `/assets`. Copy on GDrive can, but, very important; **the website will read the csv file in this repo**.

**Comment by damianooldoni** [comment]
Thanks @biekemaex and @fjasteen for your inputs about the csv file and all other visualization options. I will try to implement all of them today, but no guarantee. Tomorrow at latest.

**Comment by damianooldoni** [comment]
Issue completed by #273.
