### ISSUE TITLE
Text wrapped around image

### ISSUE THREAD

**Issue by margotvermeylen** [inbo/craywatch#211]
Is it possible to have the text starting from 'Verspreiding' not wrap around the image. For example here https://craywatch.inbo.be/soorten/astacus-astacus/ it doesn't really look good. Not sure if there is a code we can use for that.

**Comment by peterdesmet** [comment]
I have fixed this in #211. The alternative is to have images that are as wide as the text, but maybe the resolution of the images isn't good enough for that? What do you prefer?

## Current

![Gevlekte-Amerikaanse-rivierkreeft-Craywatch (1)](https://github.com/inbo/craywatch/assets/600993/2e22704c-7dd7-4edd-bdd7-423c224983db)

## Option
![Gevlekte-Amerikaanse-rivierkreeft-Craywatch](https://github.com/inbo/craywatch/assets/600993/c95a3f8a-0e9a-4967-be7d-d650a4a1a9b3)

**Comment by peterdesmet** [comment]
De (grote) foto kan ook onder de tekst indien gewenst.

**Comment by margotvermeylen** [comment]
Omdat de foto ook uitvergroot kan worden, zou ik de kleine foto misschien liever behouden. Danku!
