### ISSUE TITLE
Links invoerpagina's toevoegen

### ISSUE THREAD

**Issue by fjasteen** [inbo/craywatch#216]
De linken naar de invoerpagina's hebben deze vorm: 
[https://waarnemingen.be/events/craywatch-crayfish-indet/](voor onbekende soort)
[https://waarnemingen.be/events/craywatch-pontastacus-leptodactylus/]
etc...

Morgen worden deze geactiveerd, dus ze mogen al toegevoegd worden!

Getting closer...

**Comment by biekemaex** [comment]
closed issue because it's being tackled in #179
