### ISSUE TITLE
Make stap voor stap guide appear bigger

### ISSUE THREAD

**Issue by biekemaex** [inbo/craywatch#249]
How can I make the image that contains the stap voor stap appear bigger on this page (https://craywatch.inbo.be/waarnemingen/)? I added the option of clicking on the image to make it larger, but it would be nice if the initial image were bigger as well.

**Comment by biekemaex** [comment]
Of gaat het vanzelf veel groter verschijnen als ik de afbeelding in 2 kap? Is het mogelijk beide helften dan naast elkaar te laten verschijnen? @peterdesmet

**Comment by peterdesmet** [comment]
Ik zou de screenshot als aparte foto maken en de tekst me de stappen als tekst presenteren. Als je me dat kan geven, kan ik er een meer leesbare output van maken.

**Comment by biekemaex** [comment]
Ik weet niet of het makkelijker is dat ik de tekst al op de pagina zet of je even de link naar mijn bronbestand van de tekst stuur? https://docs.google.com/document/d/1vnTM0wUs7XpzkSd4P02QVBRbpJKntPYtoK5gBXd9A3I/edit?usp=sharing

Ik heb 2 aparte afbeeldingen van de screenshots in de map assets gezet. Ze heten screenshot_kreeft_gevangen (hoort bij deel 1 van de tekst) en screenshot_geen_kreeft (bij deel 2).

**Comment by peterdesmet** [comment]
Ik heb geen toegang tot het bestand, kan je me die geven?

**Comment by peterdesmet** [comment]
@biekemaex ik heb wat geëxploreerd met verschillende manieren om de informatie te tonen, maar ik denk dat de huidige manier de beste is: https://craywatch.inbo.be/waarnemingen/

1. Directe linken bovenaan, onder titel `Wat zat in je val?`
2. Uitleg eronder `Hoe rapporteer je een waarneming?`
3. De stappen voor een of geen kreeft zijn gecombineerd. Er is ook maar 1 screenshot.
4. De tekst is hier en daar een beetje aangepast. Gelieve na te kijken!

**Comment by biekemaex** [comment]
Ziet er goed uit! Heb jij ergens een op voorhand ingestelde code voor wat
ik er in de tekst tussen ' ' staat? Kunnen we veranderen hoe die tekst
eruit ziet? Want dat roos in een ander lettertype ziet er een beetje gek
uit. Zou dit anders in het groen (dat we ook in de banners gebruikt hebben)
en vet kunnen?

Op do 13 jun. 2024 10:41 schreef Peter Desmet ***@***.***>:

**Comment by peterdesmet** [comment]
Ander kleur kan niet. Het is het kleur voor een letterlijke waarde (zoals variabele of code) en daar hebben we geen controle over. Code maak je met `backticks`. Als je dat niet goed vind, kan je enkele of dubbele quotes gebruiken. Dat ziet het er uit als gewone tekst.

**Comment by biekemaex** [comment]
In orde, ik zal wat experimenteren, merci!

Op do 13 jun. 2024 14:56 schreef Peter Desmet ***@***.***>:
