### ISSUE TITLE
Add legend for species colors

### ISSUE THREAD

**Issue by damianooldoni** [inbo/craywatch#251]
This is a sub- issue for solving #209.

I want to add a legend with colors.

I added it with:

```js
// Add legend to the map
        var legend = L.control({position: 'bottomright'});

        legend.onAdd = function(map) {
            var div = L.DomUtil.create('div', 'legend');
            var labels = ['<strong>Species</strong>'];
            for (var species in speciesColors) {
                labels.push(
                    '<i style="background:' + speciesColors[species] + '"></i> ' +
                    species
                );
            }
            div.innerHTML = labels.join('<br>');
            return div;
        };

        legend.addTo(map);
```

But I need to add the background color and some other style features I think. Examples I got from tutorials are all referring to a `<style>` section. Something like this:

```js
<style>
  #map {
    height: 600px;
    width: 100%;
  }
  .legend {
    background: white;
    line-height: 1.5em;
    padding: 10px;
    margin: 10px;
    border-radius: 5px;
    box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
  }
  .legend i {
    width: 18px;
    height: 18px;
    float: left;
    margin-right: 8px;
    opacity: 0.7;
  }
</style>
```

@peterdesmet: Is this <style> section the best solution? If so, where should this be added?  I tried to add it before my <script> section but it doesn't work. Thanks.

**Comment by peterdesmet** [comment]
1. Yes, `<style>` is good. If we have a lot of style, we might move it to a separate css file
2. I would add it right after you load the leaflet CSS `<link>`
3. Please use `<em>` and not `<i>` (also update in your style)
