### ISSUE TITLE
Add team members

### ISSUE THREAD

**Issue by fjasteen** [inbo/craywatch#27]
Add the different team members of the Craywatch project

**Comment by peterdesmet** [comment]
Please remove or update any properties (photo, description, etc.) that do not correspond with that team member: https://craywatch.inbo.be/team/ Pretty sure @biekemaex is not "Mutant cyclops"

**Comment by margotvermeylen** [comment]
For the layout it is best to have a description by each person's name, I'm not sure what this should be though. I someone wants anything specific or has an idea, let me know.

**Comment by damianooldoni** [comment]
@timadriaens and I (@damianooldoni) will send a picture and a short description to be added to the team page. See https://craywatch.inbo.be/team/ as reference/example.

**Comment by biekemaex** [comment]
Helemaal akkoord! :)

**Comment by peterdesmet** [comment]
Merci!

```
- name: Peter Desmet
  role: Open data coördinator
  image: https://avatars1.githubusercontent.com/u/600993?s=460&v=4
  description: >
    Peter is gepassioneerd door open data en open onderzoek. Hij is open data coördinator bij het INBO's [Open science lab for biodiversity](https://oscibio.inbo.be) en biedt technische ondersteuning aan voor Craywatch.
  orcid: 0000-0002-8442-8025
  email: peter.desmet@inbo.be
  researchgate: Peter-Desmet
  mastodon: https://mastodon.social/@peterdesmet
  github: peterdesmet
```

**Comment by biekemaex** [comment]
@peterdesmet of @damianooldoni, op mijn lokaal gerenderde site ziet de foto van Tim er normaal uit, maar nu ik de commit heb doorgevoerd ziet dat er op de eigenlijke website zo uit:
![image](https://github.com/inbo/craywatch/assets/169137493/559bd174-82fa-4516-8214-0f5cc1f54df3)

Wat loopt hier mis?

**Comment by peterdesmet** [comment]
ah, dat ligt aan de hoofdletters in JPG. Ik zal even alle filenames lowercasen (can niet zo eenvoudig via GitHub Desktop).

**Comment by peterdesmet** [comment]
All images are now `lower_snake_case`. Note that a number of images are not used and are best deleted.

**Comment by damianooldoni** [comment]
Here my description: picture is, similar to @peterdesmet, an URL.

```
- name: Damiano Oldoni
  role: Onderzoekssoftware ontwikkelaar
  image: https://avatars1.githubusercontent.com/damianooldoni?s=460&v=4
  description: >
    Damiano is de trekker van de [INBO coding club](https://inbo.github.io/coding-club/) en ondersteunt onderzoekers door (open) software te schrijven. Hij is onderzoekssoftware ontwikkelaar bij INBO's [Open science lab for biodiversity](https://oscibio.inbo.be/) en biedt technische ondersteuning aan voor Craywatch.
  orcid: 0000-0003-3445-7562
  email: [damiano.oldoni@inbo.be](mailto:damiano.oldoni@inbo.be)
  researchgate: Damiano-Oldoni
  mastodon: https://fosstodon.org/@damianooldoni
  github: damianooldoni
```

**Comment by biekemaex** [comment]
@damianooldoni , I think this line "email: [damiano.oldoni@inbo.be](mailto:damiano.oldoni@inbo.be)" gave me some issue. I did it the same way as Peter did "email: peter.desmet@inbo.be" for you as well and that was accepted. I'm just wondering, should a link normally open when you click on those envelopes?

**Comment by timadriaens** [comment]
- name: Tim Adriaens
  role: Team leader Invasive Species
  Tim is gepassioneerd door biologische invasies en hun beheer. Hij is programmacoördinator invasieve soorten bij INBO en werkt vaak met citizen science. .
  orcid: 0000-0001-7268-4200
  email: [tim.adriaens@inbo.be](mailto:tim.adriaens@inbo.be)
  researchgate: Tim-Adriaens
  X: https://x.com/AdriaensTim
  github: timadriaens

**Comment by peterdesmet** [comment]
The bare email is the right approach (as you did @biekemaex ). Clicking will open an email client.
