### ISSUE TITLE
Add script for point selection and csv update to repo

### ISSUE THREAD

**Issue by fjasteen** [inbo/craywatch#270]
Margot & Bieke are selecting points through Mymaps. This maps is exported as kml and attributes are updated through an R-script before saving as the localities.csv Damiano needs for the map visualizing distribution.

This is now a seperate Rproj in a different repo (craywatcht_selection) and should be added here for version control of the localities.csv. 

@damianooldoni could you guide this noob on where to put this in the folder structure?

**Comment by peterdesmet** [comment]
No worries, I have moved it now.

**Comment by damianooldoni** [comment]
@peterdesmet , where do you suggest to put one or two R files and a Rproj file? 
The goal of this R code is to produce an output which is very important for the website, i.e. the `localities.csv` in `./assets`. So, they should be placed in this repo.
Thanks

**Comment by peterdesmet** [comment]
I would create a separate `R` or `src` directory

**Comment by damianooldoni** [comment]
Thanks, @peterdesmet.
I prefect the `R` directory.
@fjasteen: can you create a new branch with a correspondent Pull Request?
- create the folder
- add code and Rstudio project
- add the entire folder to the `exclude:` in `_config.yaml` as shown by @peterdesmet here above

Assign me as reviewer, please. I will give a look too. Thanks.

**Comment by fjasteen** [comment]
Yes, thanks Damiano. What about the './R/data/input/shapefiles/', 
I used it as a dump for all static shapefiles. Should I add the folder to the .gitignore file in the root?

**Comment by damianooldoni** [comment]
If such files are needed I would not put them in the `.gitignore` unless they contain sensitive data.
By adding a line with `- R` to the `exclude:` section in the `_config.yml` file, you will tell to jekyll that all files and subdirectories in `R` have to be excluded while generating the website.

**Comment by fjasteen** [comment]
Yes but the folder is quite giant, because of all the shapefiles, is there need to store them in the repo?

**Comment by damianooldoni** [comment]
The folder is not really big, no worries. The size of the files is also not an issue for GitHub. The biggest one is 45 MB: everything below 50MB is fine. Having everything in this repository will help the future-you to reproduce everything in the future and to maintain everything up to date. You could then also consider to remove the same files from the GDrive.

**Comment by fjasteen** [comment]
oké perfect.
What happens with the git files etc related to the current repo? Sorry for the stupid question, but I'm trying to find out how all stuff is related.

**Comment by damianooldoni** [comment]
Some standard files are indeed ignored by default in a `.gitignore`. A typical example is the `.Rhistory`. What you could do is then add all files contained in the gitignore in your repository to the `.gitignore` of this repository, **prepending the folder `R/`** as your R project is not in the root folder, but in `/R`.

**Comment by damianooldoni** [comment]
@fjasteen, @margotvermeylen: I think this has been solved last week. If you agree, please close this issue. Otherwise, let us know what has still to be done, thanks.
