### ISSUE TITLE
Embed google form onto "meld je aan" page

### ISSUE THREAD

**Issue by biekemaex** [inbo/craywatch#30]
Is it possible to embed a google form onto our website?

Damiano:
Kort antwoord: ja, het kan, zeker. Embedding is volledig mogelijk. Als je een google Form aanmaakt, en dan klik je op "Send", dan kan je kiezen voor embedding, zie screenshot:

![image](https://github.com/inbo/craywatch/assets/169137493/64c4f4bb-32ae-4657-89b2-5cd3f077e3be)

Link to google form: https://docs.google.com/forms/d/e/1FAIpQLScvWY9PY1DObsVC7O_T9pJ4bh9zoE1RUlzMrwyUOocqJUFOqA/viewform?usp=sf_link

**Comment by peterdesmet** [comment]
In what page do you want to embed this form?

**Comment by biekemaex** [comment]
This one: https://craywatch.inbo.be/aanmelden/

**Comment by biekemaex** [comment]
We updated the aanmeldpagina, would you be able to turn "Registreer je hier als burgerwetenschapper" into the button that then links to the google form? @peterdesmet

**Comment by peterdesmet** [comment]
Done, see https://craywatch.inbo.be/aanmelden/ Also fixed bugs in instructies.md (zie https://github.com/inbo/craywatch/commit/660a72bdeab97944094f1f3100ee2253ca0a82cf)
