### ISSUE TITLE
Render favicon

### ISSUE THREAD

**Issue by damianooldoni** [inbo/craywatch#4]
I don't understand why the favicon is not shown. The file `favicon.ico` is in the root as it should be. It is shown in my other website, [notes](https://damianooldoni.github.io/notes/).

**Comment by peterdesmet** [comment]
It renders for me, maybe you need to clear your cache.

**Comment by damianooldoni** [comment]
The favicon is shown. It was just blocked by DuckDuckGo Privacy Essential extension I had on my Chrome browser.
