### ISSUE TITLE
Align photos and text

### ISSUE THREAD

**Issue by biekemaex** [inbo/craywatch#40]
How can we make the text appear 2 lines lower (next to the center of the image) on the page https://craywatch.inbo.be/team/

**Comment by peterdesmet** [comment]
No. The layout will work better if you add a short `description` per person.

Also, the images `Kevin.jpg` and `Vaart.jpg` are too big. Would change resolution to 72dpi and size to 1200px max. Let me know if you want me to do that.

**Comment by margotvermeylen** [comment]
Thank you so much Peter! We can try to downsize the images, this will probably be necessary for other images in the future too. Could you direct us to a good website/way to convert this though? Thanks!

**Comment by peterdesmet** [comment]
Hmm, I just do it on my computer (a Macbook), not sure how to do it on window.

Additionally, I suggest to name the images lowercase + snakecase (underscore), so not `Craywatch met tagline.jpg` but `craywatch_met_tagline.jpg`
