### ISSUE TITLE
Layout crayfish species page

### ISSUE THREAD

**Issue by biekemaex** [inbo/craywatch#41]
Is it possible to replace the dropdown menu that includes all 8 crayfish species with just a button "rivierkreeften"?
On this rivierkreeften page we could have photos of all the different species, that you can click on to go to a page with extra information per species - cfr "beschermde natuur", "water", "bodem & lucht" on https://www.vlaanderen.be/inbo/home/

**Comment by peterdesmet** [comment]
That is possible, will try to tackle that next week. Can you provide a photo for each species (either by email, Google Drive or in `assets`)?
