### ISSUE TITLE
Add INBO and ANB logo to footer

### ISSUE THREAD

**Issue by margotvermeylen** [inbo/craywatch#43]
It would be nice to have the logo of INBO and ANB in the footer somehow (linked to their websites potentially). I don't see how I would need to do this.

**Comment by peterdesmet** [comment]
Can you provide me with the logos? Ideally they are white on transparent background.

**Comment by peterdesmet** [comment]
Thanks @damianooldoni, but all logos there are jpg (which don't support transparent background). I can't open the eps versions. Just need a png version (also for ANB).

**Comment by margotvermeylen** [comment]
<img width="375" alt="Untitled design" src="https://github.com/inbo/craywatch/assets/168713182/7273c158-4c55-4f49-8730-a9b431101c39">
Does this work?

**Comment by peterdesmet** [comment]
Eventueel, maar zal niet zo mooi zijn in de groene footer. Ik heb witte tekst op een transparante achtergrond nodig.

**Comment by margotvermeylen** [comment]
![image](https://github.com/inbo/craywatch/assets/168713182/2c4f11fa-f6ce-4df5-ba9e-9406454dd902)

**Comment by margotvermeylen** [comment]
Ik vind geen witten tekst, maar wel deze zwarte. Geen idee hoe ik hier een transparante achtergrond van maak.

**Comment by peterdesmet** [comment]
Vraag je even aan Koen Van Muylem of Nicole De Groof via email?

**Comment by biekemaex** [comment]
Ik check bij hen!

**Comment by biekemaex** [comment]
Koen stuurde me deze links, misschien kan jij kiezen welke er het beste zullen uitzien, @peterdesmet?
https://inbo.tandemvault.com/browse/logo-s-1 (er staan ook logo's voor het ANB, maar niet in het wit)
