### ISSUE TITLE
Add video to homepage

### ISSUE THREAD

**Issue by margotvermeylen** [inbo/craywatch#58]
The video still needs to be inserted under the text on the homepage when it is done. #56

**Comment by peterdesmet** [comment]
Use this code to insert:

```
<div class="ratio ratio-16x9 mb-3">
<iframe src="link-to-video" frameborder="0" allowfullscreen></iframe>
</div>
```

**Comment by margotvermeylen** [comment]
Note to self: once promo video is on youtube, link to the youtube page (file is too big to embed).
For Instructions video: ?
