### ISSUE TITLE
linken naar iasregulations op species page

### ISSUE THREAD

**Issue by fjasteen** [inbo/craywatch#61]
Tims suggestie:
Kunnen jullie bij de soorten de nodige links voorzien naar https://www.iasregulation.be/? Ook de naamgeving van de soorten (common names) hiermee in lijn brengen (https://www.iasregulation.be/350/). Het zou ook leuk zijn ergens te linken naar de species fact sheets, voorbeeld voor procky: https://www.iasregulation.be/773/download. Die zijn eigenlijk wel goed.

**Comment by biekemaex** [comment]
Ik heb bij elke kreeft waar een IAS fiche voor bestaat een link toegevoegd (de gevlekte is precies even van de site verdwenen, ik ga op zoek naar het probleem).  Voor de gestreepte heb ik ook een link toegevoegd naar het kaartje verspreiding in België. Volstaat dat qua IAS links? @fjasteen

**Comment by margotvermeylen** [comment]
Dit zou klaar moeten zijn toch @biekemaex?

**Comment by biekemaex** [comment]
Yes! Ik heb de links naar bestaande IAS fiches toegevoegd bij de verschillende soorten en we hebben een stukje over regelgeving toegevoegd. Volstaat dat voor wat je in gedachten had @fjasteen ?
