### ISSUE TITLE
Create Google Sheet for maintaining reservations

### ISSUE THREAD

**Issue by damianooldoni** [inbo/craywatch#7]
For visualization purposes and to avoid workflows involving GitHub actions, we could maintain the reservation of the pounds in a Google Sheet instead of a csv file.

Example:

locationID | isReserved | isReservedBy
--- | --- | ---
A | FALSE | 
B | TRUE | AP
C | FALSE | 
D | TRUE | DO

This Google Sheet must be **published** online (as a csv) so that the JavaScript code which generates the leaflet can retrieve it every time somebody visits the page "Locations".

**Comment by peterdesmet** [comment]
I recommend the D3 library to read the file. One of many blog posts: https://codedamn.com/news/javascript/how-to-read-csv-with-javascript

**Comment by damianooldoni** [comment]
Note for myself: test using https://docs.google.com/spreadsheets/d/e/2PACX-1vQ0oBcuDB5uC9PaTOJU8MDKHR43nhY_X8Kwt9D3yVPB1ug6p9ioc0Ss4HUzx7cevkRV4ZEscqfAHiKi/pubhtml

**Comment by damianooldoni** [comment]
@margotvermeylen: once you know who will be in charge of creating such Google Sheet, please set him/her/them as assignees.
The most important aspect of this sheet is that there will be a column where the pounds are uniquely identified. Such identifier should be the same used in the geojson file with the polygons, see #3.

**Comment by damianooldoni** [comment]
We close this issue: reservations are maintained together with all the locations. See #210
