### ISSUE TITLE
Text contains nvalid characters

### ISSUE THREAD

**Issue by margotvermeylen** [inbo/craywatch#84]
Dag Peter, 
Ik krijg weer de error dat er 'invalid characters' in mijn tekst staan op de 'info' pagina. Ik heb deze keer niet gecopy-paste uit Word maar getypt in WordPad en ik krijg hetzelfde probleem. Ik snap niet goed om welke 'characters' dit gaat en hoe ik dit best in de toekomst vermijd. Is er een manier om te identificeren waar het probleem zich bevindt?

**Comment by peterdesmet** [comment]
Ja, zoek op `Ã«` in https://github.com/inbo/craywatch/blob/main/pages/info.md (momenteel 2). In je lokale tekst editor kan het zijn dat het niet precies die zoekcombinatie is.

Kan zo'n dingen vermijden door in je tekst editor op te slaan als UTF-8 (bv in [Notepad++](https://notepad-plus-plus.org/) of [Visual Studio Code](https://code.visualstudio.com/)).
